---
- name: Create multiple users
  hosts: webservers
  become: true

  tasks: 
  - name: Create users
    user: 
      name: "{{item}}"
      state: present
    with_items:
      - user10
      - user20
      - user30

