---
- name: Installing httpd package
  hosts: webservers
  become: true

  tasks: 
  - name: Insatlling httpd package
    yum: 
      name: httpd
      state: installed
    notify: Starting httpd service

  - name: Copy index.html file
    copy:
      src: /home/ansible/index.html
      dest: /var/www/html
      mode: 0666

  handlers:
  - name: Starting httpd service
    service:
      name: httpd
      state: started



