---
- name: uninstalling httpd package
  hosts: webservers
  become: true

  tasks:
  - name: Stopping httpd service
    service:
      name: httpd
      state: stopped
  
  - name: uninsatlling httpd package
    yum: 
      name: httpd
      state: removed


