---
# tasks file for setup-apache-role
#
- name: Insatlling httpd package
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: Starting httpd service

- name: Insatlling apache2 package
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: Starting apache2 service

